### ISSUE TITLE
Add animations for player

### ISSUE THREAD

**Issue by Jonagoo** [Jonagoo/INDA-projekt#2]

**Comment by Jonagoo** [comment]
Might want to find another spritesheet, just used the first I found as a placeholder to make sure animations work.

**Comment by Nellta** [comment]
If you are going to switch to another spritesheet remember to scale it for 32x32 (or just find one which is naturally at that size), since that's the size of the tiles I'm using. This just means that we need different values for keeping the sprite from moving outside the screen.
